"""API routes for vehicle location tracking (Slice 15)."""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Path, Request, status
from pydantic import BaseModel, ConfigDict, Field

from office_hero.api.deps import require_permission
from office_hero.api.limiter import limiter
from office_hero.api.state import get_vehicle_location_repository
from office_hero.core.logging import get_logger
from office_hero.models.vehicle_location import VehicleLocation

log = get_logger(__name__)


def _tenant_id(request: Request) -> UUID:
    raw = getattr(request.state, "tenant_id", None)
    if not raw:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    return raw if isinstance(raw, UUID) else UUID(str(raw))


def _user_id(request: Request) -> UUID:
    raw = getattr(request.state, "user_id", None)
    if not raw:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    return raw if isinstance(raw, UUID) else UUID(str(raw))


class LocationUpdateRequest(BaseModel):
    """Request to update vehicle location."""

    model_config = ConfigDict(extra="forbid")

    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)
    accuracy_meters: int | None = Field(None, ge=0)
    recorded_at: datetime | None = None


class LocationResponse(BaseModel):
    """Vehicle location response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    vehicle_id: UUID
    latitude: float
    longitude: float
    accuracy_meters: int | None
    recorded_at: datetime
    created_at: datetime


def create_vehicle_location_router(*, repo_provider) -> APIRouter:
    """Construct the vehicle location router with injected providers."""
    router = APIRouter(prefix="/vehicles/{vehicle_id}/location", tags=["vehicle-location"])

    @router.put("", response_model=LocationResponse, dependencies=[Depends(require_permission("location:write"))])
    @limiter.limit("300/minute")
    async def update_location(
        request: Request,
        vehicle_id: Annotated[UUID, Path()],
        body: LocationUpdateRequest,
    ) -> LocationResponse:
        """Update vehicle GPS location (called from tech app)."""
        tenant_id = _tenant_id(request)
        repo = repo_provider()

        recorded_at = body.recorded_at or datetime.now(UTC)

        location = VehicleLocation(
            id=UUID(int=0),  # Will be generated by DB
            vehicle_id=vehicle_id,
            latitude=body.latitude,
            longitude=body.longitude,
            accuracy_meters=body.accuracy_meters,
            recorded_at=recorded_at,
            created_at=datetime.now(UTC),
        )

        try:
            created = await repo.create(tenant_id, location)
            log.info(
                "location.recorded",
                vehicle_id=str(vehicle_id),
                lat=body.latitude,
                lng=body.longitude,
                accuracy=body.accuracy_meters,
            )
            return created
        except Exception as exc:
            log.error("location.failed", vehicle_id=str(vehicle_id), error=str(exc))
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to record location",
            ) from exc

    @router.get("", response_model=LocationResponse, dependencies=[Depends(require_permission("location:read"))])
    @limiter.limit("300/minute")
    async def get_latest_location(
        request: Request,
        vehicle_id: Annotated[UUID, Path()],
    ) -> LocationResponse:
        """Get the latest location for a vehicle."""
        tenant_id = _tenant_id(request)
        repo = repo_provider()

        location = await repo.get_latest(tenant_id, vehicle_id)
        if not location:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No location found for this vehicle",
            )

        return location

    return router
