"""A generic, single‑revision migration script template generated by alembic.

This file comes from the stock alembic distribution.  It is used when
``alembic revision --autogenerate`` creates a new migration; the generated code
will substitute the revision-specific details below.
"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass


def downgrade():
    pass
